### ISSUE TITLE
Text input box for screenshot uploader clips "Remaining Characters" display - using Alternative Font tweak in settings.ini

### ISSUE THREAD

**Issue by EvilJackCarver** [somini/Pixelvision2#66] opened 2016-02-24 06:01 UTC
Having a minor issue where the top of the "Characters remaining" display is lopped off when typing. I am able to reproduce the issue across different games' screenshots, and across different screenshots of the same game. 

Screenshot of issue: 

![Screenshot of the top of the characters-remaining display being lopped off](http://i.imgur.com/xBKtotH.png)

According to the Layout tab of the F6 menu, the key is in `resource/layout/screenshotmanager.layout` and the selection is "`publish_Charsleft / Label`".

Pixelvision² build dated 2016-02-12, Windows 7 build 7601 x64, Steam client build as of 2016-02-04 12:24:44 (timezone not stated). I am using the Steam Piston and Smaller Big Picture Icon overrides. 

The following items in my settings.ini file are uncommented:
- Alternative Font
- Tweak: Game Title Background (Library, Details view)
- Tweak: Replace Big Picture Mode Icon (Use Controller Icon)

**Comment by somini** [comment] 2016-02-24 22:46
Many thanks for the extremely detailed report, you practically solved it right there.
I can confirm this, with the +3 font tweak and no overrides.
I've pushed a small fix for this to master, since it's a very localized bug, it shouldn't have far-reaching consequences. It simply increases the bottom margin on the label.

Reopen this if this hasn't fixed it for you.
And keep this hyper-detailed bug reports coming. :D

**Closed as completed** 2016-02-24 22:46 UTC

**Comment by EvilJackCarver** [comment] 2016-02-25 04:53
Confirming that the update to the screenshotmanager.layout fixed the issue, cheers for the quick response!
