### ISSUE TITLE
Nickname UI display issue

### ISSUE THREAD

**Issue by zirwin** [somini/Pixelvision2#39] opened 2015-05-18 22:32 UTC
Steps to reproduce:
1. Open the friends list
2. Click the arrow near a friend
3. Select "Add Nickname"

You'll be presented with this UI:

![image](https://cloud.githubusercontent.com/assets/568221/7691867/e0d80aae-fd72-11e4-9d59-2223c5d0c261.png)

The input box overlaps the text label.

For what it's worth, this was also the case in old PixelVision, I'm not sure if this UI changed at some point.

**Comment by somini** [comment] 2015-05-18 23:03
I can confirm this issue, but I can't really find where this screen is defined, `git grep -i nick` brings nothing.

Paging @CaptainMagma for help.

**Comment by CaptainMagma** [comment] 2015-05-18 23:14
I'll be looking into this soon, thanks for the post.

Edit: Not really sure how this is supposed to be fixed at the moment. Especially since I don't even get that problem with my skin and the file that edits this panel isn't even included in PixelVision. Do you use increased font size?

**Comment by somini** [comment] 2015-05-19 21:25
I do, +2.
In the regular font size the problem still remains, though.
![Regular Size](https://cloud.githubusercontent.com/assets/1750665/7714375/f043bd54-fe75-11e4-9b1d-6be231165af4.png)

**Comment by CaptainMagma** [comment] 2015-05-19 21:50
What resolution do you use?

**Comment by somini** [comment] 2015-05-19 21:51
1920*1080

**Comment by CaptainMagma** [comment] 2015-05-19 22:39
@somini That doesn't look like the default font in your screenshot though. And are you on Windows?

**Comment by somini** [comment] 2015-05-19 22:44
Linux actually. I did install the Segoe fonts, but Steam doesn't like to play ball with the rest of the system (#36).

**Comment by CaptainMagma** [comment] 2015-05-19 22:54
Could you try it on the default Steam skin and tell me if you still have the same issue?

**Comment by somini** [comment] 2015-05-19 23:08
It does, half way there between both screenshots in this thread.

**Comment by CaptainMagma** [comment] 2015-05-19 23:16
Alright, well the fix should be fairly simple. All I've done is moved the text box down by 10 pixels and also increased its width because I noticed it doesn't look evenly centered in the screen. I'll be submitting the pull request in a few minutes.

Edit: Let me know if this fix looks fine with your font. I only tested it with default font settings.

**Comment by somini** [comment] 2015-05-21 22:22
PR #40 fixed this, I'm closing this.

Feel free to comment or reopen in case there's some problem.

**Closed as completed** 2015-05-21 22:22 UTC
Labels: bug, help wanted
