### ISSUE TITLE
Problem of alignment using CHS

### ISSUE THREAD

**Issue by Seraphli** [somini/Pixelvision2#83] opened 2016-10-04 09:49 UTC
![](http://i1.piimg.com/567571/d54fa700aecde35a.png)

I'm using Chinese Simple as the UI language. I just download the master branch and this problem still exists. BTW, I have installed the font given in the readme.

**Comment by Psycic101** [comment] 2016-10-17 04:07
I'm not quite sure what the issue is here. I don't read "Chinese" but I don't understand what alignment issue there is in that screenshot. For what it's worth, my Steam client looks the same when Chinese Simple is selected as UI language.

**Comment by Seraphli** [comment] 2016-10-17 04:27
You can see the community icon is overlayed by the word Community. The problem is already indicated by a red rectangular.

**Comment by decaylong** [comment] 2016-11-01 05:49
Easy to fix this, just check out "locale.ini" file. Same way to other languages.

**Comment by somini** [comment] 2016-11-01 12:14
Sorry for taking so much time to respond.

@Seraphli 
As @decaylong said, can you please try edit your `locale.ini` file? Just remove the `//` on the left for you language (in your case Chinese Simplified, it's on line 31).
https://github.com/somini/Pixelvision2/blob/master/locale.ini#L31

**Comment by somini** [comment] 2016-11-01 12:26
If the problem persists, just comment here.

**Comment by Seraphli** [comment] 2016-11-02 01:46
I uncomment the line in `local.ini` and when I restart steam the icons have already been aligned. So it seems steam is not using the right style file. I don't know if you can fix that.

**Comment by somini** [comment] 2016-11-02 20:08
So you uncommented the `locale.ini` file and the problem is solved?
That's the intended way to configure it, but you only need to do it once you install the skin.

**Comment by Seraphli** [comment] 2016-11-03 01:08
Yeah, just uncommented that and it is solved. It is strange that steam is not using the right skin automatically. Why users have to configure skins by themselves? If someone try to use skins who don't understand English, they may just think that there are some problem with skins, and uninstall it.

**Comment by somini** [comment] 2016-11-03 01:12
Well, that's not our fault. We can't access the language from the skin, it requires ugly hacks like this. And Steam is not even open source, so we don't know how the default skin does it...

**Comment by somini** [comment] 2016-11-03 01:13
I'm closing this then, if you have other problems open a new issue.

**Closed as completed by somini** 2016-11-03 01:13 UTC
