### ISSUE TITLE
Notification counter clips envelope when user has a double-digit number of notifications.

### ISSUE THREAD

**Issue by EvilJackCarver** [somini/Pixelvision2#78] opened 2016-07-12 04:32 UTC
Got another minor one for ya. The notification count clips the envelope icon when I have >9 notifications.

![](https://cloud.githubusercontent.com/assets/1784490/16754975/97e944ac-47bd-11e6-94df-eb3e3b7af8c3.png)

F6 menu says it's in `/resource/layout/steamrootdialog.layout`, container `SteamRootDialog / CSteamRootDialog`, and the selection is `Inbox Button / CInboxButton`.

![](https://cloud.githubusercontent.com/assets/1784490/16755065/4e09595c-47be-11e6-86d1-009f326d13dd.png)

I'm able to replicate the issue by setting my Steam to English, so it's not a localisation issue.
![](https://cloud.githubusercontent.com/assets/1784490/16755095/9b1fcec4-47be-11e6-9435-5fb9a18e15b3.png)

Pixelvision² build dated 2016-06-29, Steam build dated 2016-07-08 14:48:42. Windows 7 build 7601 x64. I'm using the Smaller Big Picture Icon and Steam Piston overrides. 

The following items in my settings.ini are uncommented:
- Alternative Font
- Tweak: Game Title Background (Library, Details view)
- Tweak: Replace Big Picture Mode Icon (Use Controller Icon)

_N.B.: I'm about to clear out the comment notification, so that'll drop me back to 9. If you need to bring it back up to 10, let me know and I'll drop my Steam profile link - comments should be open._

**Comment by somini** [comment] 2016-07-14 23:30
Sorry for taking so long to respond, I've been busy.
Once again many thanks for such detailed bug report, we really appreciate it.

I did the easy part, just shifted the » and the counter 5 pixels to the left, should looks like it should solve the problem for less than 99 notifications. I'll ping @CaptainMagma , since I think it's possible to align the text to the right, but I couldn't do it properly.

**Comment by CaptainMagma** [comment] 2016-07-15 01:05
I believe I've commented on this issue previously in the Steam group forums. The original creator of the skin has acknowledged the existence of this bug without ever fixing it. I thought it was because he couldn't figure out a fix for it. And, honestly, I never tried to fix it because I forgot about it and I've never had that many notifications.

How's it looking now after the adjustments made?

It looks like the bug is similar to the one with the family view icon where everything after your notifications doesn't readjust its position properly. Like the family view icon bug, it could just be the Steam client's fault.

**Comment by EvilJackCarver** [comment] 2016-07-15 03:10
I've got a fresh copy-paste of [the steamrootdialog.layout uploaded 4 hours ago](https://github.com/somini/Pixelvision2/blob/89688566f040de8fecf7dcbc80418517c84d3583/resource/layout/steamrootdialog.layout) I'll need a fresh notification to check (thankfully, only one - I'm down to 9) - I'm sure I could get a few by the morning, but if you want to accelerate the process, [you can drop a comment on my steam profile - should be public](http://steamcommunity.com/profiles/76561198043243931/). 

In the meantime, I'm gonna look at the older file and get a diff and pull request ready for the Big Picture Icon override, since I know that much I should be capable of doing.

**Comment by CaptainMagma** [comment] 2016-07-15 03:54
Sure, I'll drop a comment.

**Comment by EvilJackCarver** [comment] 2016-07-15 04:05
No dice, I'm afraid - all that succeeded in doing is moving the whole thing over - icon and text. 

![](http://i.imgur.com/wnWmvUD.png)

Just in case my copy-paste botched up, the CRC32 of my local copy is 336B51A3.

**Comment by CaptainMagma** [comment] 2016-07-15 04:21
Yea, the problem is probably what I thought before. I'll try and mess around with it this weekend but I don't know if both problems can be fixed without completely re-doing the whole top right portion of the skin.

**Comment by EvilJackCarver** [comment] 2016-07-15 04:23
Alrighty. I'll stay tuned and click around in the F6 menu. If I think of something, I'll let you know. 

Might try it locally beforehand, if I can figure out what part of the skin the envelope icon is.

**Comment by CaptainMagma** [comment] 2016-07-15 04:27
You mean where the actual image file is saved? It's in the graphics folder. The files are inbox and inbox_hover.

**Comment by EvilJackCarver** [comment] 2016-07-15 05:38
I took a glance at the diff in the commit above and I'm gonna be honest - I can't make heads nor tails of it. 

Going off your suggestion, I found that adding a minimum of 5 pixels of blank space to the left of the graphic gives it enough room to clear the notifications for a double-digit amount. I went ahead and made it 7 so it'll clear comfortably.

![steam_2016-07-15_00-36-27](https://cloud.githubusercontent.com/assets/1784490/16864657/30d4bfb2-4a24-11e6-831b-0c2291a314d8.png)

It's a bit of a heavy-handed fix, and it destroys the kerning at the double-right-chevron after the "x online" bit, but it's a fix nonetheless. I've attached the TGAs, but I'm hesitant on calling it "fixed" because of the kerning issue. New dimensions are 23 wide by 12 tall.

Edit: In the morning, I'm going to revert the steamrootdialog.layout to the one from #77 and see if it fixes the kerning issue - I'd do it now but it's 00:47 and I'm having trouble thinking straight.

[notif_icon_fix.zip](https://github.com/somini/Pixelvision2/files/365271/notif_icon_fix.zip)

Edit 2016-07-15 T 17:42 Z: I reverted back to the steamrootdialog.layout for the smaller Big Picture icon override from Pull #77 (linked above) and now the envelope is realigned with the chevron above the account bit. The chevrons to the left still look a bit off (but I can deal with that). 

![steam_2016-07-15_11-45-25](https://cloud.githubusercontent.com/assets/1784490/16881824/931a6ad4-4a81-11e6-8102-d63cc187edde.png)

**One thing I realised laying down in bed, however, is that this very well may cause issues with single-digit numbers of notifications since it seems the text is aligned to the left. Push changes at own risk.**

Since the original issue is fixed with this change, feel free to close it; I won't since there still lies the chevron bit and I'd rather not decide for you guys whether this is an issue you want to fix or not.

**Comment by somini** [comment] 2016-07-15 19:32
I found a text-align property to try and align the text to the right side, but it didn't work, I commented on PR #79 .

**Comment by somini** [comment] 2016-07-15 19:39
For the record, this is what I see when I checkout `pull/79`.
![ss](https://cloud.githubusercontent.com/assets/1750665/16886443/3f9a8d44-4acc-11e6-9d08-b996087bbe6f.png)

**Comment by avsaponchik** [comment] 2016-07-16 01:23
![default](https://cloud.githubusercontent.com/assets/1337953/16891976/1716dc6a-4b0d-11e6-857d-3a3b4bfe52df.PNG)
hehe

**Comment by bykidi** [comment] 2016-07-16 01:23
hehe

**Comment by Black4Blade** [comment] 2020-10-20 17:59
Seeing that currently there are no more numbers, this issue is not relevant anymore, so going to close it up :)

**Closed as completed by Black4Blade** 2020-10-20 17:59 UTC
